server:
  port: 8001

cluster:
  nacos:
    node1: 10.6.124.134:8848

spring:
  application:
    name: study-feign-client
  cloud:
    nacos:
      discovery:
        server-addr: ${cluster.nacos.node1}
        register-enabled: true
        group: study

feign:
  hystrix:
    # 打开feign对hustrix的支持
    enabled: true

